export const tableData = [
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
  {
    nombre: 'variableA',
    tipo: 'TipoDato',
    ambito: 'Ambito',
    fila: '1',
    columna: '2',
    descErrores: 'descripcion de este error por el cual fallo la app',
    lineaError: '1',
    columnaError: '2',
    fechaError: '12121',
  },
];
