export const tableData = [
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3:
      'dato3dato3dato3dato3dato3dato3dato3dato3dato3dato3dato3dato3dato3',
    header4: 'dato4',
  },
  {
    header1: 'dato1',
    header2: 'dato2',
    header3: 'dato3',
    header4: 'dato4',
  },
];
